# Site
repository: atilsensalduz/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Atil Eren Sensalduz
title: Site Reliability Engineer
email: atil.sensalduz@gmail.com
phone: (+90)5076101994
# website: https://github.com/atilsensalduz/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  atilsensalduz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: atilerensensalduz
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/atil.jpg
about_content: | 
  As a Site Reliability Engineer with over seven years of experience, my expertise lies in managing cloud infrastructure on AWS and on-premise. I have a strong foundation in observability engineering, with a deep focus on cloud-native technologies. My technical proficiency includes the use of a wide range of tools such as Ansible, Terraform, Packer, Jenkins, CDK, Spinnaker, ArgoCD, Kubernetes, Bitbucket, and Github. I am highly skilled in automating infrastructure management and proficient in DevOps practices to manage enterprise infrastructure with a strong emphasis on application security.
  
  I specialize in observability, utilizing distributed tracing to gain insights into complex distributed systems. I have a passion for developing tools using Golang to improve my work outcomes and enhance collaboration with my team. My experience and expertise allow me to provide excellent support and solutions for complex infrastructure challenges, while ensuring the reliability and availability of services.

content:
  - title: Experience 
    layout: list
    content:
      - layout: left
        title: Hazelcast
        # link: 
        # link_text: 
        sub_title: Cloud Engineer
        caption: January 2023 - Present
        quote: >
          With a strong focus on infrastructure management and automation, coupled with expertise in Kubernetes ecosystem tools such as ArgoCD, Helm, and Prometheus, I am dedicated to optimizing cloud infrastructure and streamlining application deployments
        description: | 
          - Responsible for managing and developing the infrastructure of Hazelcast Cloud, leveraging ArgoCD and Terraform to ensure efficient deployment and management of AWS resources.
          - Utilize and have extensive experience with GitHub Actions for streamlined CI/CD workflows and version control in the development process.
          - Implement and maintain Grafana Cloud for comprehensive monitoring and utilize deep knowledge of Prometheus for effective metric collection and analysis, and leverage OpenTelemetry for distributed tracing, ensuring visibility into microservices architectures and enhancing debugging and performance optimization efforts
          - Develop Helm charts to streamline application deployment and management on Kubernetes, ensuring efficient and scalable deployments.
          - Employ external secret operators to securely manage secrets within Kubernetes, enhancing application security and access management.
          - Specialize in managing statefulset applications on Kubernetes, ensuring the reliable and optimal performance of data-intensive workloads.
          - Possess experience and expertise in working with Karpenter, enabling efficient and automated scaling of Kubernetes clusters based on workload demands.
          - Played a pivotal role in enhancing network security by working extensively on network policies, utilizing the Gadget tool to analyze workload traffic flows and generate precise network policies for secure communication.
          - Strengthened the security posture of Kubernetes clusters by enhancing securityContext configurations for workloads and ensuring compliance through rigorous checks using Kyverno.
          - Implemented a multi-architecture approach for workloads, facilitating seamless transitions of Kubernetes nodes to Graviton instances, thereby optimizing resource utilization and cost-effectiveness.
          - Utilized Falco for runtime anomaly detection, enhancing Kubernetes cluster security by monitoring and detecting suspicious activities in real-time, and fine-tuning detection rules for accurate threat identification.
          - Implemented KEDA for dynamic autoscaling of StatefulSet applications based on custom metrics, optimizing resource utilization and performance by adjusting application scaling in response to real-time demand.
          - Provisioned and managed Keycloak for secure authentication and authorization.

      - layout: left
        title: Getir
        # link: 
        # link_text: 
        sub_title: Site Reliability Engineer
        caption: April 2021 - January 2023
        quote: >
          Bringing expertise in cloud infrastructure management, DevOps processes, and observability, I strive to automate and optimize systems while ensuring reliability and performance
        description: | 
            - Managed and maintained all aspects of cloud infrastructure and streamlined DevOps processes for improved efficiency.
            - Developed command-line interface (CLI) tools and lambdas using Python and Go languages to enhance infrastructure management capabilities.
            - Utilized Bitbucket for source code management and leveraged Bitbucket pipelines to establish a robust continuous integration process.
            - Installed and configured Spinnaker, creating pipelines for seamless continuous deployment.
            - Possess a deep understanding of Kubernetes and expertise in managing Amazon EKS (Elastic Kubernetes Service).
            - Demonstrated proficiency in administering various AWS services, including IAM, VPC, Route 53, EC2, S3, ECS, CloudFront, Elasticache, Postgres RDS, Amazon MQ, and ECR.
            - Utilized OpsGenie during on-call periods to ensure effective incident response and resolution.
            - Leveraged CDK (Cloud Development Kit) for infrastructure as code, enabling efficient and scalable deployment.
            - Utilized NewRelic for comprehensive application performance monitoring and proficient in writing complex NRQL queries for in-depth analysis.
            - Possess extensive knowledge in observability practices, enabling effective monitoring and troubleshooting of distributed systems.
            - Administered MongoDB Atlas Cloud, ensuring the smooth operation and maintenance of the database infrastructure.

      - layout: left
        title: Turkcell
        # link: 
        # link_text: 
        sub_title: Senior Cloud Systems Administrator
        caption: January 2020 - April 2021
        quote: >
          With a comprehensive skill set in cloud automation, configuration management, and infrastructure orchestration, I am dedicated to driving efficiency and scalability while leveraging cutting-edge technologies
        description: | 
            - Led the end-to-end cloud automation initiatives at Turkcell Bulut, ensuring streamlined processes and efficient infrastructure management.
            - Developed PowerShell and Python scripts for effective configuration management across all infrastructure components.
            - Utilized GitLab as a source code management tool for infrastructure automation, facilitating collaboration and version control.
            - Successfully installed and configured Jenkins master and slave nodes, establishing a robust CI/CD pipeline. Managed infrastructure as code using tools such as Terraform, Packer, and Ansible.
            - Possess extensive experience with on-premises cloud platforms including vCenter, vRops, Loginsight, vRealize Orchestrator, vCloud Director, NSX, and oVirt.
            - Proficiently managed various blade and rack servers from Cisco, HP, Dell, and Huawei.
            - Demonstrated proficiency in Kubernetes and Rancher, enabling efficient container orchestration and management.
            - Worked on Openshift at the vCloud Director, adopting GitOps practices like ArgoCD and implementing cloud-native technologies such as Ceph and Helm.
            - Implemented UCS monitoring using tools like Grafana, InfluxDB, Telegraf, and Python, ensuring comprehensive visibility and performance monitoring.

      - layout: left
        title: Vakifbank
        # link: 
        # link_text: 
        sub_title: Cloud & Linux Administrator
        caption: February 2017 - January 2020
        quote: >
          With a strong background in managing on-prem cloud infrastructure, scripting automation, and resolving performance issues, I am committed to ensuring optimal functionality and efficiency of complex systems
        description: | 
            - Accountable for overseeing a sizable on-prem cloud infrastructure, comprising up to 200 servers and 4000 virtual machines, ensuring optimal performance and availability.
            - Developed and utilized shell scripts to automate day-to-day activities and tasks, enhancing operational efficiency.
            - Wrote Ansible playbooks to streamline environment management, simplifying configuration and deployment processes.
            - Possess extensive experience with on-prem cloud platforms including vCenter, vRops, Loginsight, vRealize Orchestrator, oVirt, and CloudFoundry Bosh, enabling seamless management and monitoring of infrastructure components.
            - Proficiently resolved performance issues in Linux and cloud systems, utilizing troubleshooting techniques to ensure optimal system functionality.
            - Successfully managed Cisco UCS servers, Brocade SAN switches, and storage systems from Hitachi and EMC, ensuring reliability and scalability of the infrastructure.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: Yildiz Technical University
        caption: 2012 - 2016  
        sub_title: BSc Electronic and Communication Engineering

  - title: Projects 
    layout: list
    content:
      - layout: top-middle
        title: ADR Copilot - Intelligent AI Assistant for Architectural Decision Records
        description: | 
          Designed ADR Copilot, an AI-driven solution built with Ollama, Mesop, LLMs (Llama 3.1), RAG with Hazelcast Vector Search, and LangChain to allow users to easily retrieve and explore ADRs, providing quick insights into previous architectural decisions. Automated the drafting and review process of new ADR proposals, ensuring high standards are met before submission

      - layout: top-middle
        title: Efficient Incident Response and Collaboration Enabled by a Go-powered Slack Bot
        description: | 
          Developed a robust incident management Slack bot using Go programming language, streamlining incident response and enabling efficient communication and collaboration within the team.

      - layout: top-middle
        title: Streamlining Opsgenie Management with New Relic
        description: | 
          Created an Opsgenie New Relic Exporter solution by developing Lambdas that retrieve alert and user information from Opsgenie and send it as custom events to New Relic. Designed and implemented a comprehensive dashboard to assist with Opsgenie management and facilitate data-driven decision-making.

  - title: Certifications
    layout: text
    content: | 
      <img alt="Kubestronaut" src="https://images.credly.com/size/340x340/images/cd6c6449-6814-4613-a2d3-13cf4ac5be4f/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/933f9856-7ab9-4e5d-b695-69deeedb64cc/public_url" style="color:#96989b"> Kubestronaut</a><br/>
      <img alt="CKS" src="https://images.credly.com/size/340x340/images/9945dfcb-1cca-4529-85e6-db1be3782210/kubernetes-security-specialist-logo2.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/86bdc37c-c2ce-45b9-9617-0fe991ff0fdd/public_url" style="color:#96989b"> CKS: Certified Kubernetes Security Specialist</a><br/>
      <img alt="CKA" src="https://images.credly.com/size/680x680/images/8b8ed108-e77d-4396-ac59-2504583b9d54/cka_from_cncfsite__281_29.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/a02e2f16-af50-4087-913b-f1c16d70c813/public_url" style="color:#96989b"> CKA: Certified Kubernetes Administrator</a><br/>
      <img alt="CKAD" src="https://images.credly.com/size/340x340/images/cc8adc83-1dc6-4d57-8e20-22171247e052/blob" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/9c804577-5692-4a32-ada1-a73dc65d95b6/public_url" style="color:#96989b"> CKAD: Certified Kubernetes Application Developer</a><br/>
      <img alt="KCSA" src="https://images.credly.com/size/680x680/images/67dd8a95-8876-4051-9cb9-3d97c204f85a/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/c7c01bbd-e515-44cc-9ff5-4954ffcc6963/public_url" style="color:#96989b"> KCSA: Kubernetes and Cloud Native Security Associate</a><br/>
      <img alt="KCNA" src="https://images.credly.com/size/340x340/images/f28f1d88-428a-47f6-95b5-7da1dd6c1000/KCNA_badge.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/fdf78e09-af36-49a8-9681-bdc9a40aa278/public_url" style="color:#96989b"> KCNA: Kubernetes and Cloud Native Associate</a><br/>
      <img alt="PCA" src="https://images.credly.com/size/110x110/images/c34436dc-1cfd-4125-a862-35f9c86ca17f/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/a9539f6a-5546-439c-90e4-fc085e4cd86d/public_url" style="color:#96989b"> PCA: Prometheus Certified Associate </a><br/>
      <img alt="AWS SAA" src="https://images.credly.com/images/0e284c3f-5164-4b21-8660-0d84737941bc/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/5f01cdfa-a5ef-4cf4-acf1-99602bbf4158/public_url" style="color:#96989b"> AWS Certified Solutions Architect - Associate</a><br/>
      <img alt="AWS AI Practitioner" src="https://images.credly.com/size/680x680/images/4d4693bb-530e-4bca-9327-de07f3aa2348/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/44deb8a1-c600-4aeb-8d1d-506cc4f237a0/public_url" style="color:#96989b"> AWS Certified AI Practitioner</a><br/>
      <img alt="AWS Cloud Practitioner" src="https://images.credly.com/size/680x680/images/00634f82-b07f-4bbd-a6bb-53de397fc3a6/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/32daf00e-02c4-44c0-adfa-0b1c5073b0a0/public_url" style="color:#96989b"> AWS Certified Cloud Practitioner</a><br/>
      <img alt="GitHub Administration" src="https://images.credly.com/size/680x680/images/34880f37-8ec8-4542-a78a-73ba6647208e/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/dcdc5426-69d7-485f-8c50-9fb8cd661a79/public_url" style="color:#96989b"> GitHub Administration</a><br/>
      <img alt="GitHub Copilot" src="https://images.credly.com/size/220x220/images/6b924fae-3cd7-4233-b012-97413c62c85d/blob" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/74f4505b-aa6b-48bb-aa58-a43fc35b7601/public_url" style="color:#96989b"> GitHub Copilot</a><br/>
      <img alt="Github Actions" src="https://images.credly.com/size/340x340/images/89efc3e7-842b-4790-b09b-9ea5efc71ec3/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/3b759b47-6b0a-4c9f-804d-cce90ff2049c/public_url" style="color:#96989b"> GitHub Actions</a><br/>
      <img alt="Github Advanced Security" src="https://images.credly.com/size/110x110/images/c9ed294b-f8ac-48fa-a8c3-96dab1f110f2/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/d3069881-172f-47a2-a96e-b46659d7fa8d/public_url" style="color:#96989b"> GitHub Advanced Security</a><br/>
      <img alt="Github Foundation" src="https://images.credly.com/size/340x340/images/024d0122-724d-4c5a-bd83-cfe3c4b7a073/image.png" style="width:48px;height:48px;"><a href="https://www.credly.com/badges/79d57520-ea79-4210-bed0-6cfbdc22a00d/public_url" style="color:#96989b"> GitHub Foundations</a><br/>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jemoji
 
gems:
  - jekyll-pdf
exclude :                 [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]